Lab5/LabWebMVC/LabWebMVC/Models/ErrorViewModel.cs
namespace LabWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab5/LabWebMVC/LabWebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

using LabWebMVC.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LabWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public async Task<IActionResult> PrivacyAsync()
        {
            var httpClient = new HttpClient();
            var name = User.FindFirst("name")!.Value;
            var dic = await httpClient.GetFromJsonAsync<Dictionary<string, string>>("http://192.168.88.212:5001/Account/GetUserInfo?user=" + name);


            return View("Privacy", dic);
        }

        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/LabWebMVC/LabWebMVC/Controllers/Lab1Controller.cs
using System.Diagnostics;

using LabsClassLibrary;

using LabWebMVC.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LabWebMVC.Controllers
{
    [Authorize]
    public class Lab1Controller : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public Lab1Controller(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RunLab(string input)
        {
            var result = Lab1Combination.CombineString(input);
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/LabWebMVC/LabWebMVC/Controllers/Lab2Controller.cs
using System.Diagnostics;

using LabsClassLibrary;

using LabWebMVC.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LabWebMVC.Controllers
{
    [Authorize] 
    public class Lab2Controller : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public Lab2Controller(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RunLab(string input)
        {
            if (!uint.TryParse(input, out uint N) || N <= 1 || N > 1000)
            {
                return Content("Число має бути між 1 та 1000");
            }

            var result = LabSequence.CountCombines(N);
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/LabWebMVC/LabWebMVC/Controllers/Lab3Controller.cs
using System.Diagnostics;

using LabsClassLibrary;

using LabWebMVC.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LabWebMVC.Controllers
{
    [Authorize] 
    public class Lab3Controller : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public Lab3Controller(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RunLab(string start1, string start2, string finish1, string finish2)
        {
            var result = LabPyatnashki.ComputeStepsCount(start1 + start2, finish1 + finish2);
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/LabWebMVC/LabWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Домашня сторінка";
}

<div>
    <h1 class="display-4">Вітання!</h1>
    <h3>Цей сайт - лабораторна робота</h3>
</div>
<div class="container" style="width:50%;float:left; border:1px solid lightgrey;">
    <h5>Розглянемо три алгоритми</h5>

    <a class="link-primary" asp-area="" asp-controller="Lab1" asp-action="Index"><h4>Завдання #1</h4></a>
    <h6>Алгоритм Перестановки Символів</h6>
    <p>Суть цього алгоритма полягає в тому, щоб знайти всі можливі перестановки символів</p>
    <p>Алгоритм приймає довільну кількість попарно різних символів і виводить як результат роботи всі можливі комбінаці, яки можна утворити з цих символів</p>

    <a class="link-primary" asp-area="" asp-controller="Lab2" asp-action="Index"><h4>Завдання #2</h4></a>
    <h6>Алгоритм Пошуку Комбінацій</h6>
    <p>Цей алгоритм визначає кількість можливих послідовностей довжини N, які можна утворити з 0 та 1, в яких не стоять поруч дві одиниці "11"</p>

    <a class="link-primary" asp-area="" asp-controller="Lab3" asp-action="Index"><h4>Завдання #3</h4></a>
    <h6>Алгоритм П'ятнашкі</h6>
    <p>Маємо ігрове поле 4х2, яке складається з 7 комбінацій символів і одного символа <b>#</b>, який означає пусту клітину</p>
    <p>Задача цього алгоритму полягає в тому, щоб впорядкувати вхідну кобмінацію згідно взірця за мінімальну кількість ходів</p>
</div>
 

Lab5/LabWebMVC/LabWebMVC/Views/Lab1/Index.cshtml
@{
    ViewData["Title"] = "Лаб#1";
}

<div>
    <h3>Лабораторна робота #1</h3>
</div>
<div class="container" style="border:1px solid lightgrey;">
    <h6 class="text-center">Алгоритм Перестановки Символів</h6>
    <div class="row">
        <div class="col-sm-6">
            <p>Суть цього алгоритма полягає в тому, щоб знайти всі можливі перестановки символів.</p>
            <p>Алгоритм приймає довільну кількість попарно різних символів і виводить як результат роботи всі можливі комбінаці, яки можна утворити з цих символів.</p>
            <hr />
            <p>Працює алгоритм наступним чином:</p>
            <p>
                Вхідна строка обробляється в циклі я масив символів char[]
                <br />
                Кожен символ відокремлюється в вхідної строки і потім добавляється попереду всіх можливих комбінації,
                які можна утворити з решти символів.
                Відповідно решта символів відправляється на обробку таким самим чином утворюючи рекурсію.
                Коли решта символів складається із одного символа,
                то метод обробки просто вертає список комбінацій лише з цим символом.
                Таким чином відбувається повернення уверх по ланюжку викликів список комбінацій на 1 символ більше
                допоки не утворяться всі комбінації з усіма символами.
            </p>
        </div>
        <div class="col-sm-6">
            <form id="labform">
                <div class="form-group row">
                    <label for="input" class="form-label">Введіть символи</label>

                    <div class="col-md-6">

                        <input name="input" type="text" class="form-control" id="input" placeholder="наприклад IXOF">

                    </div>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-outline-dark">Порахувати</button>

                    </div>
                </div>

            </form>
            <div id="result"></div>
        </div>
    </div>

</div>
<script>
    $("#labform").submit(function (event) {
        event.preventDefault();
        $("#result").load("@Url.Action("RunLab")", $("#labform").serialize());

    });
</script>

Lab5/LabWebMVC/LabWebMVC/Views/Lab1/RunLab.cshtml
@{
    Layout = null;
    List<string> result = Model;
}
<h6 style="margin-top:10px;">Результат (@result.Count)</h6>

@foreach (var item in result)
{
    @item <br />
}

Lab5/LabWebMVC/LabWebMVC/Views/Lab2/Index.cshtml
@{
    ViewData["Title"] = "Лаб#2";
}

<div>
    <h3>Лабораторна робота #2</h3>
</div>
<div class="container" style="border:1px solid lightgrey;">
    <h6 class="text-center">Алгоритм Перестановки Символів</h6>
    <div class="row">
        <div class="col-sm-6">
            <h6>Алгоритм Пошуку Комбінацій</h6>
            <p>Цей алгоритм визначає кількість можливих послідовностей довжини N, які можна утворити з 0 та 1, в яких не стоять поруч дві одиниці "11"</p>
            <hr />
            <p>Працює алгоритм наступним чином:</p>
            <p>
                Виходячи з того, що при утворені комбінацій довжини N ми маємо 2 рази(для 0 та 1) взяти послідовність N-1, і враховучи що при утворенні з оденицею нам підходить тільки та частина N-1, де не починається з 1, то це буде послідовсність N-2.
                <br />
                Таким чином при утворенні послідовності N ми беремо послідовність N-1 (для 0) і послідовність N-2 (для 1)
                <br />
                Утворюємо рекурсію таким чином, щоб при розрахунку для N послідовностей алгоритм обраховував суму для N-2 та N-1
                Коли пераметр рекурсії доходить до 1 то замість обрахунку вертає 2 комбінаціі, а при 0 вертає 1
                Для оптимізації обрахунку використовується кеш, тобто якщо для якогось числа N-x вже порахований результат то він зберігається і при повторному виклику просто вертає цей результат без необхідності знаву рекурсивно обраховувати.
                Цей алгоритм є варіантом послідовності фібоначчі
            </p>
        </div>
        <div class="col-sm-6">
            <form id="labform">
                <div class="form-group row">
                    <label for="input" class="form-label">Введіть Число</label>

                    <div class="col-md-6">

                        <input name="input" type="number" class="form-control" id="input" placeholder="1 < N <= 1000">

                    </div>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-outline-dark">Порахувати</button>

                    </div>
                </div>

            </form>
            <div id="result"></div>
        </div>
    </div>

</div>
<script>
    $("#labform").submit(function (event) {
        event.preventDefault();
        $("#result").load("@Url.Action("RunLab")", $("#labform").serialize());

    });
</script>

Lab5/LabWebMVC/LabWebMVC/Views/Lab2/RunLab.cshtml
@{
    Layout = null;
    var result = Model;
}
<h6 style="margin-top:10px;">Результат: @result</h6>

Lab5/LabWebMVC/LabWebMVC/Views/Lab3/Index.cshtml
@{
    ViewData["Title"] = "Лаб#3";
}

<div>
    <h3>Лабораторна робота #3</h3>
</div>
<div class="container" style="border:1px solid lightgrey;">
    <h6 class="text-center">Алгоритм П'ятнашкі</h6>
    <div class="row">
        <div class="col-sm-6">
            <h6>Алгоритм Пошуку Комбінацій</h6>
            <p>Маємо ігрове поле 4х2, яке складається з 7 комбінацій символів і одного символа <b>#</b>, який означає пусту клітину</p>
            <p>Задача цього алгоритму полягає в тому, щоб впорядкувати вхідну кобмінацію згідно взірця за мінімальну кількість ходів</p>
            <hr />
            <p>Працює алгоритм наступним чином:</p>
            <p>
                Створюється словник "ключ-значення", де ключем буде комбінація, а значенням - кількість кроків до її досягнення від початкової. Першим елементом зі значенням 0 додається початкова комбінація. Далі створюємо чергу на оброкуб в яку також додаємо першу комбінацію. Далі дістаємо черговий елемент із черги і перевіряємо чи він не відповідає кінцевому. Якщо ні, то обходимо в циклі і знаходимо всі можливі комбінації, які можна утворити із поточної згідно правил. Якщо комбінація ще не існує в словнику, то вона в нього додається зі значенням +1 від поточної, а також додається в чергу на наступний крок. Таким чином йде перебор всіх можливих комбінацій допоки не досягнемо необхідної. Якщо перебрали всі можливі комбінації, але не знайши рішення, то програма видасть результат -1;
            </p>
        </div>
        <div class="col-sm-6">
            <form id="labform">
                <div class="form-group row">
                    <label for="input" class="form-label">Перший рядок стартової комбінації</label>

                    <div class="col-md-6">
                        <input name="start1" type="text" maxlength="4" class="form-control" placeholder="ACBD">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="input" class="form-label">Другий рядок стартової комбінації</label>

                    <div class="col-md-6">
                        <input name="start2" type="text" maxlength="4" class="form-control" placeholder="32#0">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="input" class="form-label">Перший рядок взірця</label>

                    <div class="col-md-6">
                        <input name="finish1" type="text" maxlength="4" class="form-control" placeholder="ABCD">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="input" class="form-label">Другий рядок взірця</label>

                    <div class="col-md-6">
                        <input name="finish2" type="text" maxlength="4" class="form-control" placeholder="230#">
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-dark" style="margin-top:10px;">Порахувати</button>

            </form>
            <div id="result"></div>
        </div>
    </div>

</div>
<script>
    $("#labform").submit(function (event) {
        event.preventDefault();
        $("#result").load("@Url.Action("RunLab")", $("#labform").serialize());

    });
</script>

Lab5/LabWebMVC/LabWebMVC/Views/Lab3/RunLab.cshtml
@{
    Layout = null;
    var result = Model;
}
<h6 style="margin-top:10px;">Результат: @result</h6>

Lab5/LabWebMVC/LabWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabWebMVC.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark navbar-toggleable-sm bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Головна сторінка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Lab1" asp-action="Index">Завдання #1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Lab2" asp-action="Index">Завдання #2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Lab3" asp-action="Index">Завдання #3</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">@User.FindFirst("name")!.Value</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LabWebMVC
        </div>
    </footer>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    .nav-item a.nav-link:hover {
        background-color: teal;
        color: white !important;
    }
</style>